import React, { useState, useEffect, useCallback } from "react";
import { getEmployeePayments, deleteEmployeePayment } from "../services/employeePaymentService";
import EmployeePaymentForm from "../components/EmployeePaymentForm";
import jsPDF from "jspdf";

const EmployeePaymentPage = ({ darkMode = false, onUpdate }) => {
  const [payments, setPayments] = useState([]);
  const [currentPayment, setCurrentPayment] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [localDarkMode, setLocalDarkMode] = useState(darkMode);

  const fetchPayments = useCallback(async () => {
    try {
      const response = await getEmployeePayments();
      const paymentsData = Array.isArray(response.data) ? response.data : [];
      setPayments(paymentsData);
      if (onUpdate) onUpdate();
    } catch (err) {
      console.error("Error fetching payments:", err);
      setPayments([]);
    }
  }, [onUpdate]);

  useEffect(() => {
    fetchPayments();
  }, [fetchPayments]);

  useEffect(() => {
    setLocalDarkMode(darkMode);
  }, [darkMode]);

  const addOrUpdatePayment = (savedPayment) => {
    setPayments((prev) => {
      const exists = prev.find((p) => p._id === savedPayment._id);
      if (exists) {
        return prev.map((p) => (p._id === savedPayment._id ? savedPayment : p));
      } else {
        return [...prev, savedPayment];
      }
    });
    if (onUpdate) onUpdate();
  };

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this payment?")) {
      try {
        await deleteEmployeePayment(id);
        setPayments((prev) => prev.filter((p) => p._id !== id));
        if (onUpdate) onUpdate();
      } catch (err) {
        console.error("Error deleting payment:", err);
      }
    }
  };

  const handlePdfPrint = (payment) => {
    if (!payment) return;
    const doc = new jsPDF();
    
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229);
    doc.text("MediCura Medical Center", 105, 20, { align: "center" });
    
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text("Employee Payment Receipt", 105, 35, { align: "center" });
    
    doc.setDrawColor(79, 70, 229);
    doc.setLineWidth(0.5);
    doc.line(20, 42, 190, 42);
    
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    
    const startY = 55;
    const lineHeight = 10;
    
    doc.text(`Employee ID: ${payment.employeeId}`, 30, startY);
    doc.text(`Employee Name: ${payment.employeeName}`, 30, startY + lineHeight);
    doc.text(`Role: ${payment.role}`, 30, startY + lineHeight * 2);
    doc.text(`Base Salary: Rs. ${payment.baseSalary.toLocaleString()}`, 30, startY + lineHeight * 3);
    doc.text(`Attendance Days: ${payment.attendanceDays}`, 30, startY + lineHeight * 4);
    doc.text(`Total Salary: Rs. ${payment.totalSalary.toLocaleString()}`, 30, startY + lineHeight * 5);
    doc.text(`Payment Date: ${payment.paymentDate ? new Date(payment.paymentDate).toLocaleDateString() : ""}`, 30, startY + lineHeight * 6);
    doc.text(`Status: ${payment.status.toUpperCase()}`, 30, startY + lineHeight * 7);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by MediCura Employee Payment System", 105, 270, { align: "center" });
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, 280, { align: "center" });
    
    doc.save(`Payment_${payment.employeeId}_${Date.now()}.pdf`);
  };

  const clearEdit = () => setCurrentPayment(null);

  const filteredPayments = payments.filter(
    (p) =>
      p.employeeId.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.employeeName.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className={`min-h-screen p-6 transition-all duration-500 ${localDarkMode ? 'bg-gradient-to-br from-gray-900 via-indigo-900 to-gray-900' : 'bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50'}`}>
      <div className="flex justify-end mb-4">
        <button
          className={`px-6 py-3 rounded-2xl font-bold shadow-lg transform hover:scale-110 transition-all duration-300 ${
            localDarkMode ? 'bg-gradient-to-r from-yellow-400 to-orange-500 text-gray-900' : 'bg-gradient-to-r from-gray-800 to-gray-900 text-white'
          }`}
          onClick={() => setLocalDarkMode(!localDarkMode)}
        >
          {localDarkMode ? '☀️ Light Mode' : '🌙 Dark Mode'}
        </button>
      </div>

      <div className={`${localDarkMode ? 'bg-gray-800/50 backdrop-blur-xl border-gray-700' : 'bg-white/80 backdrop-blur-xl border-white/50'} rounded-3xl p-8 mb-8 shadow-2xl border transform hover:scale-[1.02] transition-all duration-300`}>
        <h1 className={`text-4xl md:text-5xl font-black mb-2 ${localDarkMode ? 'text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400' : 'text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600'}`}>
          💰 Employee Payments
        </h1>
        <p className={`${localDarkMode ? 'text-gray-300' : 'text-gray-600'} text-lg font-medium`}>
          Manage and track employee salaries efficiently
        </p>
      </div>

      <div className="mb-8">
        <EmployeePaymentForm
          currentPayment={currentPayment}
          addOrUpdatePayment={addOrUpdatePayment}
          clearEdit={clearEdit}
          darkMode={localDarkMode}
        />
      </div>

      <div className="mb-6 flex justify-center">
        <div className="relative w-full max-w-2xl">
          <input
            type="text"
            placeholder="🔍 Search by Employee ID or Name..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className={`w-full px-6 py-4 rounded-2xl font-medium shadow-lg transition-all duration-300 focus:shadow-2xl focus:scale-[1.02] ${
              localDarkMode 
                ? 'bg-gray-800/80 border-gray-700 text-white placeholder-gray-400 focus:border-purple-500' 
                : 'bg-white/90 border-gray-200 text-gray-900 placeholder-gray-500 focus:border-indigo-500'
            } border-2 outline-none backdrop-blur-xl`}
          />
        </div>
      </div>

      <div className={`${localDarkMode ? 'bg-gray-800/50 backdrop-blur-xl border-gray-700' : 'bg-white/80 backdrop-blur-xl border-white/50'} rounded-3xl shadow-2xl border overflow-hidden`}>
        <div className="overflow-x-auto">
          <table className="min-w-full">
            <thead className={`${localDarkMode ? 'bg-gradient-to-r from-purple-900 to-indigo-900' : 'bg-gradient-to-r from-indigo-600 to-purple-600'} text-white`}>
              <tr>
                {['Employee ID', 'Name', 'Role', 'Base Salary', 'Attendance', 'Total Salary', 'Payment Date', 'Status', 'Actions'].map((header) => (
                  <th key={header} className="py-4 px-6 text-left font-bold text-sm uppercase tracking-wider">
                    {header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filteredPayments.length > 0 ? (
                filteredPayments.map((p, idx) => (
                  <tr
                    key={p._id}
                    className={`${idx % 2 === 0 ? (localDarkMode ? 'bg-gray-700/30' : 'bg-indigo-50/50') : (localDarkMode ? 'bg-gray-700/10' : 'bg-white/50')} hover:${localDarkMode ? 'bg-purple-900/30' : 'bg-indigo-100/70'} transition-all duration-200 transform hover:scale-[1.01]`}
                  >
                    <td className={`py-4 px-6 font-semibold ${localDarkMode ? 'text-purple-300' : 'text-indigo-700'}`}>{p.employeeId}</td>
                    <td className={`py-4 px-6 font-medium ${localDarkMode ? 'text-white' : 'text-gray-900'}`}>{p.employeeName}</td>
                    <td className="py-4 px-6">
                      <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                        p.role === 'Doctor' ? 'bg-blue-100 text-blue-800' :
                        p.role === 'Nurse' ? 'bg-green-100 text-green-800' :
                        p.role === 'Attendant' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-purple-100 text-purple-800'
                      }`}>
                        {p.role}
                      </span>
                    </td>
                    <td className={`py-4 px-6 font-bold ${localDarkMode ? 'text-green-400' : 'text-green-600'}`}>Rs. {p.baseSalary.toLocaleString()}</td>
                    <td className={`py-4 px-6 text-center font-semibold ${localDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>{p.attendanceDays}</td>
                    <td className={`py-4 px-6 font-black text-lg ${localDarkMode ? 'text-emerald-400' : 'text-emerald-600'}`}>Rs. {p.totalSalary.toLocaleString()}</td>
                    <td className={`py-4 px-6 ${localDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>{p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : ""}</td>
                    <td className="py-4 px-6">
                      <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                        p.status === 'paid' ? 'bg-green-100 text-green-800' :
                        p.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-red-100 text-red-800'
                      }`}>
                        {p.status.toUpperCase()}
                      </span>
                    </td>
                    <td className="py-4 px-6">
                      <div className="flex flex-col md:flex-row gap-2">
                        <button
                          onClick={() => setCurrentPayment(p)}
                          className="px-4 py-2 bg-gradient-to-r from-yellow-400 to-orange-500 text-white rounded-xl font-bold hover:shadow-lg transform hover:scale-110 transition-all duration-300"
                        >
                          ✏️ Edit
                        </button>
                        <button
                          onClick={() => handleDelete(p._id)}
                          className="px-4 py-2 bg-gradient-to-r from-red-500 to-rose-600 text-white rounded-xl font-bold hover:shadow-lg transform hover:scale-110 transition-all duration-300"
                        >
                          🗑️ Delete
                        </button>
                        <button
                          onClick={() => handlePdfPrint(p)}
                          className="px-4 py-2 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-bold hover:shadow-lg transform hover:scale-110 transition-all duration-300"
                        >
                          📄 PDF
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="9" className={`py-12 text-center ${localDarkMode ? 'text-gray-400' : 'text-gray-500'} text-lg font-semibold`}>
                    <div className="flex flex-col items-center gap-4">
                      <span className="text-6xl">📭</span>
                      <span>No employee payments found</span>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default EmployeePaymentPage;